import type { Dictionary } from "./fr";

/** UI copy — English. Variables are written {name}. */
export const en: Dictionary = {
  meta: {
    title: "{product} | {brand}",
    description: "{description}",
  },
  a11y: {
    skipToContent: "Skip to content",
    close: "Close",
    decrease: "Decrease quantity",
    increase: "Increase quantity",
    previous: "Previous image",
    next: "Next image",
    zoom: "Enlarge image",
    mainNav: "Main navigation",
  },
  preview: {
    banner: "Preview: placeholder content and visuals, test-mode payments only.",
  },
  nav: {
    benefits: "Benefits",
    howItWorks: "How it works",
    details: "Details",
    offers: "Bundles",
    faq: "FAQ",
    cart: "Cart",
    cartCount: "Cart, {count} item(s)",
    switchLanguage: "Français",
    switchLanguageLabel: "Passer en français",
  },
  buy: {
    orderNow: "Order now",
    seeInAction: "See it in action",
    addToCart: "Add to cart",
    added: "Added to cart",
    variant: "Variant",
    quantity: "Quantity",
    perUnit: "/ unit",
    unitPriceAt: "that's {price} each",
    youSave: "You save {amount}",
    unavailable: "Unavailable",
    loading: "Redirecting to checkout…",
    taxesExtra: "Applicable taxes calculated at checkout.",
    taxesNone: "Prices in Canadian dollars.",
    shippingLine: "Shipping {amount} · free from {threshold}",
    shippingFree: "Free shipping",
    shippingFlat: "Shipping {amount}",
    delivery: "Estimated delivery: {min}–{max} business days",
    maxReached: "Maximum {max} units per order.",
  },
  trust: {
    securePayment: "Secure payment by Stripe",
    shipsCanada: "Ships anywhere in Canada",
    returns: "{days}-day returns",
    noAccount: "No account needed",
  },
  sections: {
    benefitsEyebrow: "Why you'll like it",
    benefitsTitle: "What it changes day to day",
    demoEyebrow: "In action",
    demoTitle: "Easy to use, in {count} steps",
    demoVideoMissing: "Demo video coming soon",
    detailsEyebrow: "Up close",
    detailsTitle: "Specs and what's in the box",
    specs: "Specifications",
    inTheBox: "What's in the box",
    zoomHint: "Tap an image to enlarge it",
    offersEyebrow: "Bundles",
    offersTitle: "Choose your bundle",
    offersSubtitle: "The unit price drops as you add more. You can mix variants in the cart.",
    reassuranceTitle: "Shop with confidence",
    reviewsTitle: "Customer reviews",
    faqEyebrow: "FAQ",
    faqTitle: "Your questions, answered",
    finalEyebrow: "Ready to order?",
    finalTitle: "Checkout takes seconds",
  },
  offers: {
    units: "{count} unit",
    unitsPlural: "{count} units",
    bestValue: "Best unit price",
    save: "Save {amount} ({percent}%)",
    reference: "Regular price",
    choose: "Order this bundle",
    select: "Choose this bundle",
    selected: "Selected bundle",
  },
  reassurance: {
    paymentTitle: "Secure payment",
    paymentText: "Payments are processed by Stripe. We never see or store your card details.",
    shippingTitle: "Tracked shipping",
    shippingText: "We ship to every province and territory. Estimated {min}–{max} business days, with tracking emailed to you.",
    supportTitle: "Customer support",
    supportText: "Have a question? Write to us. {response}",
    returnsTitle: "Returns",
    returnsText: "You have {days} days after delivery to request a return. See our return policy.",
  },
  faqGeneral: {
    shippingQ: "How much is shipping?",
    shippingA: "{shipping}. The exact amount is shown in the cart and on the checkout page, before you pay.",
    delayQ: "How long does delivery take?",
    delayA: "Allow {pmin}–{pmax} business days for processing, then {tmin}–{tmax} business days in transit: {min}–{max} business days in total. Tracking is emailed as soon as your order ships.",
    returnsQ: "Can I return the product?",
    returnsA: "Yes, you can request a return within {days} days of delivery. Full conditions are in our return policy.",
    paymentQ: "Which payment methods do you accept?",
    paymentA: "You pay on Stripe's secure checkout page, which shows the payment methods available for your order (including credit and debit cards).",
    accountQ: "Do I need an account?",
    accountA: "No. Just enter your email and shipping address at checkout.",
    taxesQ: "Are taxes included?",
    taxesExtra: "Applicable taxes for your province are calculated and shown on the checkout page before you confirm.",
    taxesNone: "The total shown in the cart and on the checkout page is the final amount you pay.",
  },
  cart: {
    title: "Your cart",
    empty: "Your cart is empty.",
    continue: "Continue shopping",
    remove: "Remove",
    subtotal: "Subtotal",
    savings: "Bundle savings",
    shipping: "Shipping",
    free: "Free",
    freeShippingRemaining: "{amount} away from free shipping.",
    freeShippingReached: "You've unlocked free shipping.",
    taxes: "Taxes",
    taxesAtCheckout: "Calculated at checkout",
    total: "Total",
    totalBeforeTax: "Total before tax",
    checkout: "Checkout",
    secureNote: "Secure payment by Stripe · No account needed",
  },
  errors: {
    generic: "Checkout couldn't start. Please try again in a moment.",
    rate_limited: "Too many attempts. Please wait a few minutes and try again.",
    payments_unavailable: "Checkout is temporarily unavailable. Please try again later or contact us.",
    invalid: "Your cart had an invalid item. It has been updated — please review it and try again.",
    too_many: "Maximum quantity exceeded ({max} units per order).",
    network: "Connection failed. Check your network and try again.",
  },
  success: {
    title: "Thank you for your order!",
    orderNumber: "Order number",
    confirming: "We're confirming your payment with Stripe… This page updates automatically.",
    paid: "Payment confirmed. You'll receive a summary email, then your tracking number once it ships.",
    processing: "Your payment is being processed by your bank. We'll email you once it's confirmed — no action needed.",
    failed: "The payment didn't go through and no order was placed. You can try again from the store.",
    unknown: "We haven't received Stripe's confirmation yet. If you paid, it will arrive shortly; otherwise, contact us with the email you used.",
    nextSteps: "Next steps",
    step1: "Payment confirmed by Stripe",
    step2: "Packed and shipped within {min}–{max} business days",
    step3: "Tracking number emailed to you",
    back: "Back to the store",
  },
  cancel: {
    title: "Checkout cancelled",
    text: "You haven't been charged. Your cart is saved — pick up where you left off whenever you like.",
    backToCart: "Back to cart",
    back: "Back to the store",
  },
  footer: {
    contact: "Contact",
    shipping: "Shipping",
    returns: "Returns",
    privacy: "Privacy",
    terms: "Terms of sale",
    rights: "All rights reserved.",
    payments: "Secure payments by Stripe. Prices in Canadian dollars.",
  },
  pages: {
    toComplete: "To complete before launch",
    lastUpdated: "Last updated: {date}",
  },
};
