/** Textes de l'interface — français (langue par défaut). Les variables s'écrivent {nom}. */
export const fr = {
  meta: {
    title: "{product} | {brand}",
    description: "{description}",
  },
  a11y: {
    skipToContent: "Aller au contenu",
    close: "Fermer",
    decrease: "Diminuer la quantité",
    increase: "Augmenter la quantité",
    previous: "Image précédente",
    next: "Image suivante",
    zoom: "Agrandir l'image",
    mainNav: "Navigation principale",
  },
  preview: {
    banner: "Aperçu : contenu et visuels provisoires, paiements en mode test uniquement.",
  },
  nav: {
    benefits: "Avantages",
    howItWorks: "Fonctionnement",
    details: "Détails",
    offers: "Offres",
    faq: "FAQ",
    cart: "Panier",
    cartCount: "Panier, {count} article(s)",
    switchLanguage: "English",
    switchLanguageLabel: "Switch to English",
  },
  buy: {
    orderNow: "Acheter maintenant",
    seeInAction: "Voir le produit en action",
    addToCart: "Ajouter au panier",
    added: "Ajouté au panier",
    variant: "Variante",
    quantity: "Quantité",
    perUnit: "/ unité",
    unitPriceAt: "soit {price} l'unité",
    youSave: "Vous économisez {amount}",
    unavailable: "Indisponible",
    loading: "Redirection vers le paiement…",
    taxesExtra: "Taxes applicables calculées au paiement.",
    taxesNone: "Prix en dollars canadiens.",
    shippingLine: "Livraison {amount} · gratuite dès {threshold}",
    shippingFree: "Livraison gratuite",
    shippingFlat: "Livraison {amount}",
    delivery: "Livraison estimée : {min} à {max} jours ouvrables",
    quantityDeals: "Rabais quantité (tous coloris et tailles confondus)",
    quantityDealsCart: "Le rabais se calcule sur le total d'unités du panier.",
    maxReached: "Maximum {max} unités par commande.",
  },
  trust: {
    securePayment: "Paiement sécurisé par Stripe",
    shipsCanada: "Livraison partout au Canada",
    returns: "Retours sous {days} jours",
    noAccount: "Aucun compte requis",
  },
  sections: {
    benefitsEyebrow: "Pourquoi l'adopter",
    benefitsTitle: "Ce que le produit change au quotidien",
    demoEyebrow: "En action",
    demoTitle: "Simple à utiliser, en {count} étapes",
    demoVideoMissing: "Vidéo de démonstration à venir",
    detailsEyebrow: "Dans le détail",
    detailsTitle: "Caractéristiques et contenu du colis",
    specs: "Caractéristiques",
    inTheBox: "Contenu du colis",
    zoomHint: "Touchez une image pour l'agrandir",
    offersEyebrow: "Offres",
    offersTitle: "Choisissez votre lot",
    offersSubtitle: "Le prix unitaire baisse avec la quantité. Vous pouvez combiner les variantes dans le panier.",
    reassuranceTitle: "Acheter en toute confiance",
    reviewsTitle: "Avis de clients",
    faqEyebrow: "Questions fréquentes",
    faqTitle: "Vos questions, nos réponses",
    finalEyebrow: "Prêt à commander ?",
    finalTitle: "Votre commande en quelques secondes",
  },
  offers: {
    units: "{count} unité",
    unitsPlural: "{count} unités",
    bestValue: "Meilleur prix unitaire",
    save: "Économie de {amount} ({percent} %)",
    reference: "Prix de référence",
    choose: "Commander ce lot",
    select: "Choisir ce lot",
    selected: "Lot sélectionné",
  },
  reassurance: {
    paymentTitle: "Paiement sécurisé",
    paymentText: "Le paiement est traité par Stripe. Nous ne voyons ni ne stockons vos données de carte.",
    shippingTitle: "Livraison suivie",
    shippingText: "Expédition vers toutes les provinces et territoires. Délai estimé de {min} à {max} jours ouvrables, numéro de suivi envoyé par courriel.",
    supportTitle: "Service client",
    supportText: "Une question ? Écrivez-nous. {response}",
    returnsTitle: "Retours",
    returnsText: "Vous avez {days} jours après réception pour demander un retour. Voir la politique de retour.",
  },
  faqGeneral: {
    shippingQ: "Combien coûte la livraison ?",
    shippingA: "{shipping}. Le montant exact s'affiche dans le panier et sur la page de paiement, avant de payer.",
    delayQ: "Quel est le délai de livraison ?",
    delayA: "Comptez {pmin} à {pmax} jours ouvrables de préparation, puis {tmin} à {tmax} jours ouvrables de transport, soit {min} à {max} jours ouvrables au total. Vous recevez le numéro de suivi par courriel dès l'expédition.",
    returnsQ: "Puis-je retourner le produit ?",
    returnsA: "Oui, vous pouvez demander un retour dans les {days} jours suivant la réception. Les conditions détaillées figurent dans notre politique de retour.",
    paymentQ: "Quels moyens de paiement acceptez-vous ?",
    paymentA: "Le paiement se fait sur la page sécurisée de Stripe, qui affiche les moyens de paiement disponibles pour votre commande (cartes de crédit et de débit notamment).",
    accountQ: "Dois-je créer un compte ?",
    accountA: "Non. Il suffit d'indiquer votre courriel et votre adresse de livraison au moment du paiement.",
    taxesQ: "Les taxes sont-elles incluses ?",
    taxesExtra: "Les taxes applicables selon votre province sont calculées et affichées sur la page de paiement, avant la validation.",
    taxesNone: "Le total affiché au panier et sur la page de paiement est le montant final que vous payez.",
  },
  cart: {
    title: "Votre panier",
    empty: "Votre panier est vide.",
    continue: "Continuer mes achats",
    remove: "Retirer",
    subtotal: "Sous-total",
    savings: "Économie sur la quantité",
    shipping: "Livraison",
    free: "Gratuite",
    freeShippingRemaining: "Plus que {amount} pour la livraison gratuite.",
    giftRemaining: "Plus que {amount} pour recevoir : {gift}.",
    giftReached: "{gift} : offert avec votre commande !",
    freeShippingReached: "Livraison gratuite atteinte.",
    taxes: "Taxes",
    taxesAtCheckout: "Calculées au paiement",
    total: "Total",
    totalBeforeTax: "Total avant taxes",
    checkout: "Passer au paiement",
    secureNote: "Paiement sécurisé par Stripe · Aucun compte requis",
  },
  errors: {
    generic: "Le paiement n'a pas pu démarrer. Réessayez dans un instant.",
    rate_limited: "Trop de tentatives. Patientez quelques minutes avant de réessayer.",
    payments_unavailable: "Le paiement est temporairement indisponible. Réessayez plus tard ou contactez-nous.",
    invalid: "Votre panier contient un article invalide. Il a été mis à jour, vérifiez-le avant de réessayer.",
    too_many: "Quantité maximale dépassée ({max} unités par commande).",
    network: "Connexion impossible. Vérifiez votre réseau et réessayez.",
  },
  success: {
    title: "Merci pour votre commande !",
    orderNumber: "Numéro de commande",
    confirming: "Nous confirmons votre paiement auprès de Stripe… Cette page se met à jour automatiquement.",
    paid: "Paiement confirmé. Un courriel récapitulatif vous sera envoyé, puis le numéro de suivi dès l'expédition.",
    processing: "Votre paiement est en cours de traitement par votre banque. Nous vous écrirons dès sa confirmation ; aucune action n'est requise.",
    failed: "Le paiement n'a pas abouti. Aucune commande n'a été validée. Vous pouvez réessayer depuis la boutique.",
    unknown: "Nous n'avons pas encore reçu la confirmation de Stripe. Si vous avez payé, elle arrivera sous peu ; sinon, contactez-nous avec l'adresse courriel utilisée.",
    nextSteps: "Prochaines étapes",
    step1: "Confirmation du paiement par Stripe",
    step2: "Préparation et expédition sous {min} à {max} jours ouvrables",
    step3: "Numéro de suivi envoyé par courriel",
    back: "Retour à la boutique",
  },
  cancel: {
    title: "Paiement annulé",
    text: "Aucun montant n'a été prélevé. Votre panier est conservé : vous pouvez reprendre votre commande quand vous voulez.",
    backToCart: "Revenir au panier",
    back: "Retour à la boutique",
  },
  footer: {
    contact: "Contact",
    shipping: "Livraison",
    returns: "Retours",
    privacy: "Confidentialité",
    terms: "CGV",
    tracking: "Suivi de commande",
    rights: "Tous droits réservés.",
    payments: "Paiements sécurisés par Stripe. Prix en dollars canadiens.",
  },
  announce: {
    freeShipping: "Livraison gratuite",
    returns: "{days} jours satisfait ou remboursé",
    secure: "Paiement sécurisé",
    canada: "Livré partout au Canada",
    delivery: "Livraison en {min}–{max} jours ouvrables",
  },
  hero: {
    reviews: "{avg}/5 · {count} avis",
    discount: "-{percent} %",
    compareAt: "Prix habituel",
    gallery: "Galerie du produit",
  },
  blocks: {
    reassurance: { shipping: "Livraison gratuite", shippingText: "{min}–{max} jours ouvrables, suivie", payment: "Paiement sécurisé", paymentText: "Traité par Stripe", returns: "Retours {days} jours", returnsText: "Satisfait ou remboursé", support: "Support", supportText: "En français, par courriel" },
    illustration: "Images d'illustration.",
    problemEyebrow: "Le problème",
    featuresEyebrow: "Caractéristiques",
    featuresTitle: "Ce qu'il fait, concrètement",
    howEyebrow: "Mode d'emploi",
    howTitle: "Comment ça marche",
    reviewsEyebrow: "Avis clients",
    reviewsTitle: "Ce qu'en disent les clients",
    verified: "Achat vérifié",
    yes: "Oui",
    no: "Non",
    faqTitle: "Questions fréquentes",
    finalTitle: "Prêt à passer à l'action ?",
    finalPrice: "{price} · livraison gratuite",
  },
  tracking: {
    title: "Suivi de commande",
    intro: "Entrez votre numéro de commande (ex. BR-7K2Q9M) et l'adresse courriel utilisée lors du paiement.",
    orderNumber: "Numéro de commande",
    email: "Courriel",
    submit: "Suivre ma commande",
    loading: "Recherche…",
    notFound: "Aucune commande ne correspond à ces informations. Vérifiez le numéro et le courriel.",
    rateLimited: "Trop de recherches. Réessayez dans quelques minutes.",
    status: "Statut",
    carrier: "Transporteur",
    trackingNumber: "Numéro de suivi",
    trackLink: "Suivre le colis chez le transporteur",
    placedOn: "Commande du {date}",
    steps: { paid: "Paiement confirmé", processing: "En préparation", shipped: "Expédiée", delivered: "Livrée" },
    pending: "Paiement en attente de confirmation",
    failed: "Paiement non abouti",
    cancelled: "Commande annulée",
  },
  sizeGuide: {
    eyebrow: "Guide des tailles",
    title: "Trouve la bonne taille",
    open: "Guide des tailles →",
    close: "Fermer ✕",
    unit: "Unité de mesure",
    cm: "CM",
    inches: "POUCES",
    size: "Taille",
    chest: "Tour de poitrine",
    back: "Longueur du dos",
    unitCm: "cm",
    unitIn: "po",
    note: "Mesure le tour de poitrine à l'endroit le plus large et le dos du cou à la base de la queue. Entre deux tailles, prends la plus grande.",
    pickSize: "Taille",
    sizeRequired: "Choisis une taille pour continuer.",
    color: "Coloris",
    selected: "Taille sélectionnée : {size}",
  },
  pages: {
    toComplete: "À compléter avant publication",
    lastUpdated: "Dernière mise à jour : {date}",
  },
};

export type Dictionary = typeof fr;
